version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: insurance-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - insurance-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: insurance-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/insurance
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - insurance-network

  mongo:
    image: mongo:6
    container_name: insurance-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=insurance
    networks:
      - insurance-network

  nginx:
    image: nginx:alpine
    container_name: insurance-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - insurance-network

volumes:
  mongo-data:

networks:
  insurance-network:
    driver: bridge